# Copyright (C) 2023-2026 Pain001. All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR MIT
#
# Licensed under either of the Apache License, Version 2.0 or the MIT
# License, at your option. You may not use this file except in
# compliance with one of those licences. Copies are provided in
# LICENSE-APACHE and LICENSE-MIT.
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the Licences is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the applicable Licence for the specific language
# governing permissions and limitations.

"""No restricted Swift or bank material may live in this repository.

Bank usage guidelines, CBPR+ and CGI-MP are published on MyStandards
under restricted terms. Those documents (PDF, XSD, Excel, zip) stay
outside the repository in the maintainer's own storage and nothing
derived from a bank's guideline is committed; the corpus ships public
rulebook content only. This test walks the tracked tree and fails on
any file that looks like one of those exports.
"""

from __future__ import annotations

import re
import subprocess
from pathlib import Path

import pytest

REPO = Path(__file__).resolve().parent.parent
FORBIDDEN_NAME_PARTS = (
    "mystandards",
    "swift.cbprplus",
    "cgi-mp",
    "_externalcodesets_",
    "usage_guideline",
    "usageguideline",
)
FORBIDDEN_SUFFIXES = (".pdf", ".xlsx", ".zip")
FORBIDDEN_DIRS = ("scenarios", "pain001/corpus")
#: Text signatures of a MyStandards export.
SIGNATURES = (
    b"generated by MyStandards",
    b"swift.cbprplus",
)
#: MyStandards exports are named ``<publisher>_<message>_...``.
EXPORT_NAME = re.compile(r"_(pain|pacs|camt)\.\d{3}", re.IGNORECASE)


def _tracked_files() -> list[Path]:
    out = subprocess.run(
        ["git", "ls-files", "-z"], cwd=REPO, capture_output=True, check=True
    ).stdout
    return [REPO / p.decode() for p in out.split(b"\0") if p]


def test_no_restricted_export_is_tracked() -> None:
    """No tracked path is named like a MyStandards export."""
    offenders = [
        p
        for p in _tracked_files()
        if any(part in p.name.lower() for part in FORBIDDEN_NAME_PARTS)
        or EXPORT_NAME.search(p.name)
    ]
    assert offenders == [], f"restricted material tracked: {offenders}"


def test_no_binary_document_under_corpus_or_scenarios() -> None:
    """PDF, Excel and zip files never belong under the corpus trees."""
    offenders = [
        p
        for p in _tracked_files()
        if p.suffix.lower() in FORBIDDEN_SUFFIXES
        and any(str(p.relative_to(REPO)).startswith(d) for d in FORBIDDEN_DIRS)
    ]
    assert offenders == []


@pytest.mark.parametrize("suffix", [".xsd", ".xml", ".yaml", ".json"])
def test_no_tracked_file_carries_a_mystandards_signature(suffix: str) -> None:
    """A guideline schema or sample would carry one of the signatures."""
    offenders = []
    for path in _tracked_files():
        if path.suffix != suffix or not path.exists():
            continue
        data = path.read_bytes()
        if any(sig in data for sig in SIGNATURES):
            offenders.append(path.relative_to(REPO))
    assert offenders == [], f"MyStandards signature in: {offenders}"


def test_gitignore_blocks_the_exports() -> None:
    """The ignore rules are in place so a stray copy is never staged."""
    text = (REPO / ".gitignore").read_text(encoding="utf-8")
    for pattern in (
        "*MyStandards*",
        "*_pain.[0-9]*",
        "*swift.cbprplus*",
        "*CGI-MP*",
    ):
        assert pattern in text
