name: Feature Request
description: Suggest an enhancement for pain001
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
    validations:
      required: true
  - type: textarea
    id: use_case
    attributes:
      label: Real-World Use Case
    validations:
      required: true
  - type: dropdown
    id: breaking_change
    attributes:
      label: Breaking Change?
      options:
        - "No"
        - "Yes"
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
  - type: textarea
    id: contribution
    attributes:
      label: Willingness To Contribute

